### ISSUE TITLE
[BUG]: ModuleNotFoundError when using  tensorflow 2.17.0. 

### ISSUE THREAD

**Issue by Arritmic** [serengil/retinaface#106]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/retinaface/issues) and [closed issues](https://github.com/serengil/retinaface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### RetinaFace's Version

0.0.17

### Python Version

3.10.14

### Operating System

Ubuntu 24.04 LTS

### Dependencies

tensorboard==2.17.0
tensorboard-data-server==0.7.2
tensorflow==2.17.0
tensorflow-io-gcs-filesystem==0.37.1
retina-face==0.0.17

### Reproducible example

```Python
hasFrame, frame = cap.read()
resp = RetinaFace.detect_faces(frame)
print(resp)
```

### Relevant Log Output

```
Traceback (most recent call last):
  File "/home/myspace/anaconda3/envs/myenv/lib/python3.10/site-packages/retinaface/commons/package_utils.py", line 19, in validate_for_keras3
    import tf_keras
ModuleNotFoundError: No module named 'tf_keras'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bla/bla/bla/scripts/MMST_Face_Detection_Module.py", line 39, in <module>
    from retinaface import RetinaFace
  File "/home/myspace/anaconda3/envs/myenv/lib/python3.10/site-packages/retinaface/RetinaFace.py", line 20, in <module>
    package_utils.validate_for_keras3()
  File "/home/myspace/anaconda3/envs/myenv/lib/python3.10/site-packages/retinaface/commons/package_utils.py", line 24, in validate_for_keras3
    raise ValueError(
ValueError: You have tensorflow 2.17.0 and this requires tf-keras package. Please run `pip install tf-keras` or downgrade your tensorflow.
```

### What happened instead?

After installing tf-keras (2.17.0), it seems it works:
```

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1723724774.766310  421430 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
24-08-15 15:26:16 - Directory /home/myspace/.deepface created
24-08-15 15:26:16 - Directory /home/myspace/.deepface/weights created
24-08-15 15:26:16 - retinaface.h5 will be downloaded from the url https://github.com/serengil/deepface_models/releases/download/v1.0/retinaface.h5
Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/retinaface.h5
To: /home/myspace/.deepface/weights/retinaface.h5
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 119M/119M [00:04<00:00, 29.6MB/s]
{'face_1': {'score': 0.9993606805801392, 'facial_area': [796, 138, 856, 223], 'landmarks': {'right_eye': [817.68085, 179.61206], 'left_eye': [845.1754, 174.52724], 'nose': [837.74194, 191.97112], 'mouth_right': [825.0055, 206.98227], 'mouth_left': [846.4441, 203.29948]}}}

```

**Comment by serengil** [comment]
Exception message is clear `You have tensorflow 2.17.0 and this requires tf-keras package. Please run `pip install tf-keras` or downgrade your tensorflow.`

What makes you think this is a bug?

**Comment by Arritmic** [comment]
Hi, 
Probably wrong label from my side. My apologies. 
I just wanted to point that maybe would be nice to update the requirements or installation dependencies.

Best.

**Comment by serengil** [comment]
I cannot because if we add tf_keras dependency then users with tf < 2.17 will have trouble.
