### ISSUE TITLE
ValueError: The channel dimension of the inputs should be defined. Found `None`.

### ISSUE THREAD

**Issue by fanchunpeng** [serengil/retinaface#2]
Traceback (most recent call last):
  File "unit-tests.py", line 10, in <module>
    resp = RetinaFace.detect_faces(img, threshold = 0.5)
  File "D:\Face_Capture\Server33_Live\RetinaFace\retinaface-master\retinaface\RetinaFace.py", line 54, in detect_faces
    model = build_model()
  File "D:\Face_Capture\Server33_Live\RetinaFace\retinaface-master\retinaface\RetinaFace.py", line 30, in build_model
    retinaface_model.build_model(),
  File "D:\Face_Capture\Server33_Live\RetinaFace\retinaface-master\retinaface\model\retinaface_model.py", line 486, in build_model
    ssh_c2_aggr = Conv2D(filters = 256, kernel_size = (3, 3), name = 'ssh_c2_aggr', strides = [1, 1], padding = 'VALID', use_bias = True)(ssh_c2_aggr_pad)
  File "D:\python_fancp\Anaconda3.7\lib\site-packages\keras\engine\base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "D:\python_fancp\Anaconda3.7\lib\site-packages\keras\layers\convolutional.py", line 132, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.

**Comment by serengil** [comment]
what was your tensorflow version?

**Comment by quqixun** [comment]
Same issue happend while using nvidia-tensorflow==1.15.4+nv20.11 with cuda11.1 on rtx3080, Ubuntu18.04.

**Comment by thanhpt93** [comment]
update tensorflow==2.0 version can solve this problem
