### ISSUE TITLE
Error importing retineface

### ISSUE THREAD

**Issue by 007rohitSaini** [serengil/retinaface#22]
>>>from retinaface import RetinaFace
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\retinaface\RetinaFace.py", line 10, in <module>
    import tensorflow as tf
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\__init__.py", line 46, in <module>    
    from tensorflow.python import data
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\data\__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 99, in <module>
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 140, in <module>    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 25, in <module>    from tensorflow.python.data.experimental.ops import compression_ops
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 20, in <module>    from tensorflow.python.data.util import structure
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\data\util\structure.py", line 26, in <module>    from tensorflow.python.data.util import nest
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\data\util\nest.py", line 40, in <module>    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 28, in <module>    from tensorflow.python.framework import constant_op
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\framework\constant_op.py", line 29, in <module>    from tensorflow.python.eager import execute
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\eager\execute.py", line 27, in <module>    from tensorflow.python.framework import dtypes
  File "C:\Users\ROHIT\anaconda3\envs\jarvis\lib\site-packages\tensorflow\python\framework\dtypes.py", line 32, in <module>    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
        () -> handle

**Comment by serengil** [comment]
your tensorflow installation seems problematic

**Comment by 007rohitSaini** [comment]
i tried reinstalling tensorflow and got this error
tf_version = int(tf.__version__.split(".")[0])
AttributeError: module 'tensorflow' has no attribute '__version__'

**Comment by serengil** [comment]
what is your tf version?

**Comment by 007rohitSaini** [comment]
i have 2.5.0 i tried installing 2.2.0 but again got an error
ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.0 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.8.0rc0, 2.8.0rc1)
ERROR: No matching distribution found for tensorflow==2.2.0

**Comment by serengil** [comment]
closed due to inactivity
