### ISSUE TITLE
Error when call RetinaFace.detect_faces

### ISSUE THREAD

**Issue by hungnmai** [serengil/retinaface#29]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/retinaface/RetinaFace.py", line 90, in detect_faces
    net_out = model(im_tensor)
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'model/bn_data/FusedBatchNormV3' defined at (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/retinaface/RetinaFace.py", line 90, in detect_faces
      net_out = model(im_tensor)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/engine/base_layer.py", line 982, in error_handler
      def __call__(self, *args, **kwargs):
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/engine/base_layer.py", line 987, in error_handler
      **kwargs: Keyword arguments to be passed to `self.call`.
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/engine/functional.py", line 452, in call
      inputs, training=training, mask=mask)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/engine/functional.py", line 589, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/layers/normalization/batch_normalization.py", line 767, in call
      outputs = self._fused_batch_norm(inputs, training=training)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/layers/normalization/batch_normalization.py", line 624, in _fused_batch_norm
      training, train_op, _fused_batch_norm_inference)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/utils/control_flow_util.py", line 106, in smart_cond
      pred, true_fn=true_fn, false_fn=false_fn, name=name)
    File "/home/ubuntu/anaconda3/envs/dev/lib/python3.7/site-packages/keras/layers/normalization/batch_normalization.py", line 613, in _fused_batch_norm_inference
      data_format=self._data_format)
Node: 'model/bn_data/FusedBatchNormV3'
cuDNN launch failure : input shape ([1,3,1024,1222])
	 [[{{node model/bn_data/FusedBatchNormV3}}]] [Op:__inference_function_7605]

**Comment by serengil** [comment]
it seems an environmental problem

please re-try for the libraries with version "opencv-python==3.4.4", "tensorflow==1.9.0"

**Comment by serengil** [comment]
closed due to inactivity
