### ISSUE TITLE
Get AttributeError: 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by madityarafip** [serengil/retinaface#30]
```
Traceback (most recent call last):
File "face_service.py", line 101, in face_detection    
    bboxes = RetinaFace.detect_faces(image)
File "/usr/local/lib/python3.8/dist-packages/retinaface/RetinaFace.py", line 91, in detect_faces
    net_out = [elt.numpy() for elt in net_out]
File "/usr/local/lib/python3.8/dist-packages/retinaface/RetinaFace.py", line 91, in <listcomp>
    net_out = [elt.numpy() for elt in net_out]
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 401, in __getattr__
    self.__getattribute__(name)
AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Comment by serengil** [comment]
please provide more information e.g. your input image and your code

**Comment by serengil** [comment]
closed due to inactivity
