### ISSUE TITLE
retinaface is not importing. pls help

### ISSUE THREAD

**Issue by JacobTauro** [serengil/retinaface#33]
Python 3.9.12 (main, Mar 24 2022, 13:02:21) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import retinaface
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andy/Desktop/img check/retinaface.py", line 1, in <module>
    from retinaface import RetinaFace
ImportError: cannot import name 'RetinaFace' from partially initialized module 'retinaface' (most likely due to a circular import) (/home/andy/Desktop/img check/retinaface.py)

**Comment by JacobTauro** [comment]
Thank u
